### ISSUE TITLE
add last_polling_command

### ISSUE THREAD

**Issue by ananyevgv** [syssi/esphome-apc-ups#7]
I looked through your code, added several sensors (12). changed last_polling_command (27). The sensor polling time has increased. Can the number of sensors (required) be added to the component setup?

apc_ups:
  - id: ups0
    uart_id: uart_0
    last_polling_command: 15

**Comment by ananyevgv** [comment]
![image](https://github.com/syssi/esphome-apc-ups/assets/81970899/be6361e0-1de6-40b1-bf0a-dec927b8abbe)

**Comment by ananyevgv** [comment]
![image](https://github.com/syssi/esphome-apc-ups/assets/81970899/3b6e6df6-2a71-417d-9bf2-6da95d7f9feb)

**Comment by ananyevgv** [comment]
I added the sensors to your code a little bit, and a question arose with the number of sensors and their survey

**Comment by ananyevgv** [comment]
![image](https://github.com/syssi/esphome-apc-ups/assets/81970899/10fcda49-16ae-4190-8015-50d6ce639da2)

**Comment by syssi** [comment]
Because of the slow baud rate the slow update interval (1 req/s) is recommended. Some APC UPSs doesn't respond anymore if the client is too fast. Don't try to speed up the update interval.

**Comment by syssi** [comment]
Are you happy or do you still miss something?
